#!/usr/bin/env python3
import random
''''
The traditional "Rock paper and scissors" game was developed in Python.
The user must fight the computer in the game's single player mode.

The program prompts the user to choose between rock-paper-scissors options. 

Then the computer also randomly selects a selection for itself. The software will then decide who is the winner according to the rules of the game.

There are no complicated features or graphical user interfaces in this software.



August 5, 2023

'''' 

options = ("rock", "paper", "scissors") # list of options for the computer
running = True

while running:
	    player = None
        computer = random.choice(options)

    # Looping through until the player enters a valid choice among "rock", "paper", and "scissors"
    while player not in options:
        player = input("Enter rock, paper or scissors): ")
   
    print(f"Player: {player}")
    print(f"Computer: {computer}")

      if player == computer:
        print("It is a tie!")
    elif player == "rock" and computer == "scissors":
        print("You Win")
    elif player == "paper" and computer == "rock":
        print("You Win")
    elif player == "scissors" and computer == "paper":
        print("You Win")
    else:
        print("You Lost :(")

    # Asking the player if they want to play again, and breaking the loop otherwise
    if not input("Would you like play again? (y/n): ") == "y":
        running = False

print("You are an amazing player!")